apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-app
  labels:
    app: appointment-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-app
  template:
    metadata:
      labels:
        app: appointment-app
    spec:
      containers:
      - name: appointment-app
        image: your-dockerhub-username/appointment-app:latest  # Replace with your Docker Hub image
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        env:
        - name: FLASK_ENV
          value: "production"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: appointment-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: appointment-app
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
