apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  labels:
    app: appointment-app
spec:
  type: LoadBalancer
  selector:
    app: appointment-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
